import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cookie Policy | Dellics Travels',
  description: 'Read the Cookie Policy for Dellics Travels.',
};

export default function CookiesPage() {
  return (
    <article className="prose prose-slate prose-a:text-brand-orange max-w-none">
      
      <div dangerouslySetInnerHTML={{ __html: `<p><strong>                                                                COOKIE POLICY</strong></p><p><strong>Our cookie promise</strong></p><p>We'll only ever use cookies and similar technologies - such as tags and pixels - for the purposes set out in this Cookie Policy (“Policy”) and will never use them to inflate or alter the prices you see when searching on Dellics Travels or to manipulate demand.</p><p><strong>About this policy</strong></p><p>Along with our <a class="text-blue-600 hover:underline" href="https://www.skyscanner.net/terms-of-service?market=gh" target="_blank">Terms of Service</a> and <a class="text-blue-600 hover:underline" href="https://www.skyscanner.net/gh/en-gb/ghs/media/privacy-policy" target="_blank">Privacy Policy</a>, this Policy provides you with information about the cookies and other similar technologies that are used by all of our websites, and other services. We'll review this policy from time to time to make sure it's up-to-date. If we make changes, we'll post the latest version here. When we make significant changes, we'll let you know when you next access our services, or by other communications.</p><p><strong>How do we use cookies and similar technologies?</strong></p><p>We use cookies and similar technologies when you use our services, including the mobile app (“App”) and the Dellics Travels website (such as Dellicstravels.com) (<strong>“Website”</strong>) (together, our <strong>“Platforms”</strong>). These are controlled either by us or directly by third parties acting on our behalf or independently.</p><p><strong>Learn more about cookies and similar technologies</strong></p><p><strong>What cookies and similar technologies do we use and how can you opt out of them?</strong></p><p>Dellics Travels uses cookies and similar technologies to help provide services to you, learn more about them and your rights in relation to them.</p><p><strong>Click here to see the cookies and similar technologies we use</strong></p><p><strong>How can I withdraw my consent to the use of cookies and similar technologies?</strong></p><p>When you access our services for the first time on your device, we ask you to agree to us using cookies and similar technologies in line with this policy. If you don't agree to our use of these technologies, or you change your mind at a later date, you can withdraw your consent using the methods set out in this Policy or alternatively, stop using our services.</p><p><strong>Learn more about opting-in or opting-out of cookies and similar tracking technologies</strong></p><p><strong>More information</strong></p><p>If you have any questions regarding this Policy or would like more information about the cookies used on our Website or App, please <a class="text-blue-600 hover:underline" href="https://help.skyscanner.net/hc/requests/new" target="_blank">contact us</a>.</p>` }} />
    </article>
  );
}